### ISSUE TITLE
Incorrect bundle when used aliases

### ISSUE THREAD

**Issue by iKBAHT** [substack/watchify#177] opened 2015-04-01 16:21 UTC
In config I use browserify b.require function to create aliases to files, like this require('./vendor/angular/angular.js', {expose: 'angular'}). When I start watchify, and change one of "aliased" files than my bundle was generate incorrectly.
I find that if off caching in watchify then bundle starts generate correctly.

**Comment by arusakov** [comment] 2015-04-01 17:02
watchify + aliases will be very usefull for me too!

**Comment by zertosh** [comment] 2015-04-01 17:06
Can you give me something I can reproduce?

**Comment by zertosh** [comment] 2015-04-11 22:48
@iKBAHT @arusakov Did you figure it out?

**Comment by iKBAHT** [comment] 2015-04-12 19:25
The example https://github.com/iKBAHT/browserify-watch-bug-example

**Comment by zertosh** [comment] 2015-04-12 20:18
@iKBAHT your test def breaks something. I'm not a grunt user, nor am I familiar with how grunt-browserify does it's alias thing. So it'll take me a bit to dig into it. Is there any chance you can make another sample repo that uses the plain browserify/watchify api?

**Comment by iKBAHT** [comment] 2015-04-13 09:12
Ok, I'll try

**Comment by iKBAHT** [comment] 2015-04-14 08:14
@zertosh now example work on native browesrify and watchify api https://github.com/iKBAHT/browserify-watch-bug-example
If set bOpts.cache = false (line 26 in Gruntfile.js) then example starts work

**Comment by zertosh** [comment] 2015-04-19 04:10
@iKBAHT your repo was fantastic! Thank you! So it's actually not a bug with watchify, but instead with module-deps (used by browserify). I fixed it in https://github.com/substack/module-deps/pull/80 - hopefully that'll get merged soon.

**Comment by golojads** [comment] 2015-04-20 09:08
Same problem with aliases exists in grunt-browserify, but cache option is exposed through browserifyOptions and can be altered. 

ref: http://stackoverflow.com/questions/29735873/grunt-browserify-alias-stop-working/29743426#29743426

**Comment by substack** [comment] 2015-04-20 20:09
Merged the fix in module-deps. Closing.

**Closed by substack** 2015-04-20 20:09 UTC
Labels: bug
