### ISSUE TITLE
Error: EPERM, rename '...something...'

### ISSUE THREAD

**Issue by dfcreative** [substack/watchify#83] opened 2014-08-15 10:52 UTC
I use watchify as a npm task in windows, and periodically it stops watching and logs
```
{ [Error: EPERM, rename 'c:\Users\dmitry\Dropbox\Projects\mod\dist\mod.js']
  errno: 50,
  code: 'EPERM',
  path: 'c:\\Users\\dmitry\\Dropbox\\Projects\\mod\\dist\\mod.js' }
```
Restarting fixes it for a while utill the next EPERM error.

**Comment by gnack** [comment] 2015-01-20 05:14
+1, first reported on 15th Aug 2014 and still no official fix...

**Comment by jonathancloudshare** [comment] 2015-01-26 12:56
+1

**Comment by EugeneZ** [comment] 2015-01-26 16:31
+1, I had this issue and using the fork @manuelcabral recommended above fixed it.

**Comment by rchanou** [comment] 2015-01-26 17:08
+1 This is part of the reason I've been using webpack instead.

**Comment by flq** [comment] 2015-02-06 13:06
:+1: same here, annoying bug.

**Comment by ryan1234** [comment] 2015-03-09 19:26
+1. Trying to fork from @manuelcabral  and if that doesn't work, it's webpack time.

**Comment by liddellj** [comment] 2015-03-13 10:01
I'm seeing this as well using 2.4.0 on Windows 7 using Sublime.

**Comment by Larzans** [comment] 2015-03-13 12:15
+1

PhpStorm, Windows 7, the first time it compiles without problem, but as soon as i change something and the compilation start, it reports the blocked file.

As long as watchify is running i can't do anything with the file, windows reports ownership as "unable to determine" and doesn't let me do anything with it.

Restarting watchify makes it compile once, but as soon as i chang sth. it is the same all over again, rendering watchify virtually useless.

It started hapening yesterday, after investigating a while i couldn't make out any change i made to the system other that adding and including a new file to my project, very strange indeed...

**Comment by Larzans** [comment] 2015-03-14 15:43
As i mentioned before, the error occurred every time i changed a file and watchify kicked in, i didn't install or updated anything previous to the first time the error occurred, i simply added more code (via an extra module).

Removing some modules and therefore reducing the compile / clean time let the problem disappear, so it seems to be related to the time the different tasks need.

In my case, every time my clean task took more than x ms, i would get the EPERM message.
```javascript
gulp.task('clean', function () {
    return gulp.src( './dist/' )
    .pipe(vinylPaths(del))
    .on('error', gutil.log);
});
```

I don't know why that is, but this seems to be the trigger (tested with various complexities of my program).

Maybe somebody better versed in gulp can figure this one out.

**Comment by ArtskydJ** [comment] 2015-03-14 16:18
Anyone who is interested (@liddellj, @ryan1234, @flq) can give me feedback on [my watchify fork](https://github.com/ArtskydJ/watchify/tree/fix-eperm). It just retries the rename if there is an error.

I'm planning to make a PR, but I'm having trouble replicating the `EPERM` with watchify, so I don't know if this fixes it. If you test my fork, you should see `retrying` and not `EPERM` in the log.

I also have to clean up the logs before I make the PR.

To test:

1. clone the fork
2. checkout the `fix-eperm` branch
3. run `npm link` to give you the command

**Comment by Larzans** [comment] 2015-03-14 17:43
cmd.js not cli.js ;)

**Comment by ArtskydJ** [comment] 2015-03-14 19:15
Thanks, fixed.

**Comment by zertosh** [comment] 2015-03-26 03:11
I _think_ I've got a fix for this in https://github.com/substack/watchify/pull/169 - _think_ because I've only tested it in a Win7 VM. Can a few of you give it a test drive and comment on the PR? I'd like to merge this fix in fast so I can get these other goodies out https://github.com/substack/watchify/issues/168

**Closed** 2015-03-26 14:59 UTC
Labels: bug

**Comment by zertosh** [comment] 2015-03-26 15:05
The fix was published as watchify@2.6.2

**Comment by davepile** [comment] 2015-03-26 19:17
watchify@2.6.2 on win 8.1  looks good! 

Just tested saving a file with an error then correcting the error and resaving several times. No problems.
Nice work, thanks.

**Comment by flq** [comment] 2015-03-26 21:37
Just had an extensive session on a Windows10 Preview VM, no problems. Definitely a much nicer experience, thanks for the work!

**Comment by mherodev** [comment] 2015-12-16 02:41
I am seeing this issue as long as the folder the file is contained in is open in Sublime Text 3. I'm not certain if this is an issue with the editor, watchify or something else, unfortunately.

**Comment by mherodev** [comment] 2015-12-16 10:33
This issue only exists in Windows (reproduced on Windows 7); on Ubuntu I do not encounter the same permissions issues.
